export const TRADE_CATEGORIES = [
  { value: "electrician", label: "Electrician" },
  { value: "plumber", label: "Plumber" },
  { value: "hvac", label: "HVAC" },
  { value: "painter", label: "Painter" },
  { value: "drywall", label: "Drywall" },
  { value: "flooring", label: "Flooring" },
  { value: "roofer", label: "Roofer" },
  { value: "landscaper", label: "Landscaper" },
  { value: "carpenter", label: "Carpenter" },
  { value: "concrete", label: "Concrete" },
  { value: "framing", label: "Framing" },
  { value: "masonry", label: "Masonry" },
  { value: "insulation", label: "Insulation" },
  { value: "siding", label: "Siding" },
  { value: "windows", label: "Windows & Doors" },
  { value: "tile", label: "Tile" },
  { value: "cabinets", label: "Cabinets" },
  { value: "demolition", label: "Demolition" },
  { value: "excavation", label: "Excavation" },
  { value: "other", label: "Other" },
];

export const TRADE_TAGS_BY_CATEGORY = {
  electrician: [
    "Panel Upgrade",
    "Lighting",
    "Rough-in",
    "Service Calls",
    "Generator",
    "Low Voltage",
    "EV Charger",
    "Solar",
    "Commercial",
    "Residential",
  ],
  plumber: [
    "Water Heater",
    "Rough-in",
    "Service Calls",
    "Sewer",
    "Gas Lines",
    "Repiping",
    "Drain Cleaning",
    "Fixture Install",
    "Commercial",
    "Residential",
  ],
  hvac: [
    "Install",
    "Service",
    "Ductwork",
    "Mini-Split",
    "Refrigeration",
    "Commercial",
    "Residential",
    "Repair",
    "Maintenance",
    "New Construction",
  ],
  painter: [
    "Interior",
    "Exterior",
    "Commercial",
    "Residential",
    "Cabinet Painting",
    "Wallpaper",
    "Staining",
    "Power Washing",
    "Deck Staining",
  ],
  drywall: [
    "Hanging",
    "Finishing",
    "Texturing",
    "Repair",
    "Commercial",
    "Residential",
    "Acoustic Ceiling",
    "Metal Framing",
  ],
  flooring: [
    "Hardwood",
    "Tile",
    "Carpet",
    "Vinyl",
    "Laminate",
    "LVP",
    "Refinishing",
    "Commercial",
    "Residential",
  ],
  roofer: [
    "Shingles",
    "Metal",
    "Flat Roof",
    "TPO",
    "EPDM",
    "Repair",
    "Inspection",
    "Commercial",
    "Residential",
    "Gutters",
  ],
  landscaper: [
    "Design",
    "Maintenance",
    "Irrigation",
    "Hardscaping",
    "Tree Service",
    "Lawn Care",
    "Snow Removal",
    "Commercial",
    "Residential",
  ],
  carpenter: [
    "Framing",
    "Finish",
    "Trim",
    "Decks",
    "Stairs",
    "Custom",
    "Commercial",
    "Residential",
  ],
  concrete: [
    "Flatwork",
    "Foundations",
    "Driveways",
    "Patios",
    "Stamped",
    "Commercial",
    "Residential",
  ],
  framing: [
    "Wood Framing",
    "Metal Framing",
    "Structural",
    "Commercial",
    "Residential",
  ],
  masonry: [
    "Brick",
    "Block",
    "Stone",
    "Repair",
    "Commercial",
    "Residential",
  ],
  insulation: [
    "Spray Foam",
    "Fiberglass",
    "Cellulose",
    "Commercial",
    "Residential",
  ],
  siding: [
    "Vinyl",
    "Fiber Cement",
    "Wood",
    "Metal",
    "Commercial",
    "Residential",
  ],
  windows: [
    "Installation",
    "Replacement",
    "Repair",
    "Commercial",
    "Residential",
  ],
  tile: [
    "Floor",
    "Wall",
    "Backsplash",
    "Shower",
    "Commercial",
    "Residential",
  ],
  cabinets: [
    "Custom",
    "Installation",
    "Refinishing",
    "Commercial",
    "Residential",
  ],
  demolition: [
    "Interior",
    "Exterior",
    "Selective",
    "Commercial",
    "Residential",
  ],
  excavation: [
    "Site Prep",
    "Grading",
    "Utilities",
    "Commercial",
    "Residential",
  ],
  other: [
    "General",
    "Commercial",
    "Residential",
  ],
};